### PR TITLE
Cleanup CSS vendor prefixes

### PR DESCRIPTION
**Pull request by Daft-Freak**
A little cleanup. (Basically ran through PostCSS with the default browserlist.)

### CODE REVIEW

**Comment by botanicvelious** [comment]
I think that some of that css is used and cant just be removed?

**Comment by Daft-Freak** [comment]
The target I used covers [these](https://browsersl.ist/?q=%3E+0.5%25%2C+last+2+versions%2C+Firefox+ESR%2C+not+dead), and support for all the standard rules goes back to around Firefox 29, Chrome 36, Safari 9 and IE 10.

**Comment by botanicvelious** [comment]
As this is the code for the current site I'm thinking to leave it for now, and just fix all that for oga3.

As we can use something like pure.css for oga3 that will handle all the backward compatibility I don't know if its a good idea to break something that people may be using currently without some sort of plan

**Comment by botanicvelious** [comment]
I for some reason thought this was the OGA2 theme... looks fine then

**Pull request merged**
